config/routes.rb
SampleApp::Application.routes.draw do
  resources :todos

  root 'todos#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @todo }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:description, :finished)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.haml
= form_for @todo do |f|
  - if @todo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@todo.errors.count, "error")} prohibited this todo from being saved:"
      %ul
        - @todo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :finished
    = f.check_box :finished
  .actions
    = f.submit 'Save'

app/views/todos/edit.html.haml
%h1 Editing todo

= render 'form'

= link_to 'Show', @todo
\|
= link_to 'Back', todos_path

app/views/todos/index.html.haml
%h1 Listing todos

%table
  %tr
    %th Description
    %th Finished
    %th
    %th
    %th

  - @todos.each do |todo|
    %tr
      %td= todo.description
      %td= todo.finished
      %td= link_to 'Show', todo
      %td= link_to 'Edit', edit_todo_path(todo)
      %td= link_to 'Destroy', todo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Todo', new_todo_path

app/views/todos/new.html.haml
%h1 New todo

= render 'form'

= link_to 'Back', todos_path

app/views/todos/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @todo.description
%p
  %b Finished:
  = @todo.finished

= link_to 'Edit', edit_todo_path(@todo)
\|
= link_to 'Back', todos_path